# Values for register clusters
# NOTE: on-cloud nodes created by register clusters will have alibabacloud.com/external=true label

deploy:
  accessKey:
    enabled: true
    secretName: alibaba-addon-secret
    idKey: access-key-id
    secretKey: access-key-secret
  newProvisionerToken: false

# deployment
controller:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 2
      preference:
        matchExpressions:
        - key: type
          operator: NotIn
          values:
          - virtual-kubelet
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        # csi-provisioner should be scheduled to on-cloud nodes
        - key: alibabacloud.com/external
          operator: In
          values:
          - "true"

# daemonset
nodePools:
  default:
    pluginname: csi-plugin
    nodeSelectorTerms:
      - matchExpressions:
        - key: type
          operator: NotIn
          values:
            - virtual-kubelet
        - key: alibabacloud.com/external
          operator: In
          values:
            - "true"
  external:
    pluginname: ack-csi-plugin
    deploy:
      ecs: false
      # don't need the accessKey on off-cloud nodes
      accessKey:
        enabled: false
    csi:
      disk:
        enabled: false
    nodeSelectorTerms:
      - matchExpressions:
        - key: type
          operator: NotIn
          values:
            - virtual-kubelet
        - key: alibabacloud.com/external
          operator: DoesNotExist

