[files]
extend-exclude = ["vendor/*", "*.mod", "*.sum", "build/", "staging/"]

[default]
binary = false


[default.extend-words]
teh = "teh"
ded = "ded"
eles = "eles"
TAGED = "TAGED"
Entrie = "Entrie"
DescribeFilesetsResponseBodyEntriesEntrie = "DescribeFilesetsResponseBodyEntriesEntrie"