kind: Service
apiVersion: v1
metadata:
  name: csi-lvm-provisioner
  namespace: kube-system
  labels:
    app: csi-lvm-provisioner
spec:
  selector:
    app: csi-lvm-provisioner
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-lvm-provisioner
  namespace: kube-system
spec:
  serviceName: "csi-lvm-provisioner"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-lvm-provisioner
    spec:
      tolerations:
      - operator: Exists
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      priorityClassName: system-node-critical
      serviceAccount: alicloud-csi-plugin
      containers:
        - name: csi-provisioner
          image: registry.cn-hangzhou.aliyuncs.com/acs/csi-provisioner:v1.2.0
          args:
            - "--provisioner=lvmplugin.csi.alibabacloud.com"
            - "--csi-address=$(ADDRESS)"
            - "--volume-name-prefix=lvm"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/lvmplugin.csi.alibabacloud.com/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/lvmplugin.csi.alibabacloud.com
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/lvmplugin.csi.alibabacloud.com
            type: DirectoryOrCreate
  updateStrategy:
    type: RollingUpdate