apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-dbfs-config
  labels:
    alicloud-pvname: csi-dbfs-config
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: dbfsplugin.csi.alibabacloud.com
    volumeHandle: d-2ze4tf94z3fkeg6ttv52-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.dbfsplugin.csi.alibabacloud.com/zone
          operator: In
          values:
          - cn-hangzhou-a