name: Update Dockerfile
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    name: Update Dockerfile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: make update-dockerfile
    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update Dockerfile"
        git push -f origin HEAD:update-dockerfile
